services:
  postgres:
    image: postgres:16
    container_name: logisync-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logisync
    ports:
      - "5432:5432"
    volumes:
      - logisync-pg:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: logisync-redis
    ports:
      - "6379:6379"
    volumes:
      - logisync-redis:/data

volumes:
  logisync-pg:
  logisync-redis:
